2024-09-13 03:35:46,440 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 03:35:47,686 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 16:34:59,140 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 16:34:59,141 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 16:34:59,142 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 16:34:59,142 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 16:39:38,762 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 16:39:38,761 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 16:39:38,764 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 16:39:38,765 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 16:50:59,265 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 16:51:00,545 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 17:06:04,657 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 17:06:04,798 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 17:06:04,894 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 17:06:04,902 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 17:11:58,796 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 17:11:58,797 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 17:11:58,799 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-13 17:11:58,803 INFO: Microblog startup [in /home/ubuntu/microblog_EC2_deployment/app/__init__.py:94]
2024-09-14 03:15:26,377 ERROR: Exception on / [GET] [in /home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 865, in full_dispatch_request
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 1239, in preprocess_request
  File "/home/ubuntu/microblog_EC2_deployment/app/main/routes.py", line 22, in before_request
    g.locale = str(get_locale())
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask_babel/__init__.py", line 265, in get_locale
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask_babel/__init__.py", line 209, in default_locale
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 350, in parse
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 335, in _try_load
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 204, in __init__
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 75, in exists
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 42, in normalize_locale
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 93, in locale_identifiers
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/locale-data'
2024-09-14 03:16:41,560 ERROR: Exception on / [GET] [in /home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 865, in full_dispatch_request
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 1239, in preprocess_request
  File "/home/ubuntu/microblog_EC2_deployment/app/main/routes.py", line 22, in before_request
    g.locale = str(get_locale())
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask_babel/__init__.py", line 265, in get_locale
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask_babel/__init__.py", line 209, in default_locale
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 350, in parse
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 335, in _try_load
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 204, in __init__
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 75, in exists
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 42, in normalize_locale
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 93, in locale_identifiers
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/locale-data'
2024-09-14 03:18:36,864 ERROR: Exception on /auth/login [GET] [in /home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 865, in full_dispatch_request
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 1239, in preprocess_request
  File "/home/ubuntu/microblog_EC2_deployment/app/main/routes.py", line 22, in before_request
    g.locale = str(get_locale())
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask_babel/__init__.py", line 267, in get_locale
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 350, in parse
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 335, in _try_load
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 204, in __init__
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 75, in exists
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 42, in normalize_locale
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 93, in locale_identifiers
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/locale-data'
2024-09-14 03:20:09,734 ERROR: Exception on /auth/login [GET] [in /home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 865, in full_dispatch_request
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask/app.py", line 1239, in preprocess_request
  File "/home/ubuntu/microblog_EC2_deployment/app/main/routes.py", line 22, in before_request
    g.locale = str(get_locale())
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/flask_babel/__init__.py", line 267, in get_locale
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 350, in parse
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 335, in _try_load
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/core.py", line 204, in __init__
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 75, in exists
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 42, in normalize_locale
  File "/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/localedata.py", line 93, in locale_identifiers
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/microblog_EC2_deployment/virtual/lib/python3.9/site-packages/babel/locale-data'
